version: "3.7"

# registry.digitalocean.com/integrated-systems-registry/integrated-systems/leptos:v0.1

services:
  leptos-ui:
    image: registry.digitalocean.com/integrated-systems-registry/integrated-systems/leptos:latest
    container_name: leptos-ui
    depends_on:
     - sqlserver
     - dotnet-api
    ports:
     - "3000:3000"

  dotnet-api:
    image: registry.digitalocean.com/integrated-systems-registry/integrated-systems/dotnet-api:latest
    container_name: dotnet-api
    depends_on:
     - sqlserver
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
    ports:
     - "80:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: ish_server
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: Integrated-Systems-Password-123
      ACCEPT_EULA: Y
    volumes:
      - ish_data:/var/opt/mssql/data


volumes:
  ish_data:
    driver: local