version: "3.7"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: ish_server
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: Integrated-Systems-Password-123
      ACCEPT_EULA: Y
    volumes:
      - ish_data:/var/opt/mssql/data


volumes:
  ish_data:
    driver: local